# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: frodrig2 <frodrig2@student.42porto.com>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/04/17 10:12:31 by frodrig2          #+#    #+#              #
#    Updated: 2026/04/17 10:13:26 by frodrig2         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
FILES = ft_display_file.c ft_putchar.c

all:
	@cc -Wall -Wextra -Werror -o ${NAME} ${FILES}

clean:
	@rm -f *.o

fclean:
	@rm -f $(NAME)
